### PR TITLE
Add support for NOTIN with ListCondition

### PR DESCRIPTION
**Pull request by AhmedFawzy**
Please merge it as soon as possible :)

### CODE REVIEW

**Comment by bgaillard** [comment]
Hi @AhmedFawzy, thanks for this, this will be in version `1.6.0` soon.

**Comment by bgaillard** [comment]
Oups, I merged this but had to revert this. 

I'm not sure `NOTIN` should be supported with the LIST condition. In the official Remote Guide http://docs.pushwoosh.com/docs/createmessage they only indicate that IN operator is supported for the LIST condition.

So are you sure `NOTIN` is supported, If yes could you provide a link which shows this ?

@FallDi could you indicate us if `NOTIN` is supported for `LIST` ? 

Thanks

**Comment by FallDi** [comment]
We support **only** IN operator for LIST tag. NOTIN operator support is not planned. http://docs.pushwoosh.com/docs/createmessage#section-list-tags

**Comment by bgaillard** [comment]
:+1: Hi @FallDi, ok thanks for clarification on this, so we made the right decision here.

**Pull request merged**
