### PR TITLE
Allow Symfony 3.0

### PR DESCRIPTION
**Pull request by vinkla**

### CODE REVIEW

**Comment by bgaillard** [comment]
Hi @vinkla, I though your changes would work but it does not build with PHP 5.4.

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for symfony/stopwatch v3.0.0 -> satisfiable by symfony/stopwatch[v3.0.0].
    - symfony/stopwatch v3.0.0 requires php >=5.5.9 -> your PHP version (5.4.45) or "config.platform.php" value does not satisfy that requirement.
  Problem 2
    - Installation request for symfony/yaml v3.0.0 -> satisfiable by symfony/yaml[v3.0.0].
    - symfony/yaml v3.0.0 requires php >=5.5.9 -> your PHP version (5.4.45) or "config.platform.php" value does not satisfy that requirement.
  Problem 3
    - symfony/stopwatch v3.0.0 requires php >=5.5.9 -> your PHP version (5.4.45) or "config.platform.php" value does not satisfy that requirement.
    - satooshi/php-coveralls v0.6.1 requires symfony/stopwatch >=2.2 -> satisfiable by symfony/stopwatch[v3.0.0].
    - Installation request for satooshi/php-coveralls v0.6.1 -> satisfiable by satooshi/php-coveralls[v0.6.1].
```

Why do you need Symphony 3.0 here ?

**Comment by vinkla** [comment]
I need it for the Laravel integration. Maybe we make the least PHP requirement 5.5.9? PHP 5.4 is no longer supported and will not receive any security fixes since of september this year.

**Comment by bgaillard** [comment]
Ok I totally agree with you on this (http://php.net/supported-versions.php). 

I propose to create a new `1.3.0` version of the library with a minimum `5.5` PHP version.

**Comment by vinkla** [comment]
Sounds good! Use `5.5.9` since that is the least required version of symphony.

**Pull request merged**
