### PR TITLE
Update travis php versions

### PR DESCRIPTION
**Pull request by vinkla**
We actually have to testa against PHP 5.3.3 since that is the version we're targeting in `composer.json`.

### CODE REVIEW

**Comment by vinkla** [comment]
:+1:

**Comment by bgaillard** [comment]
Oups build failed because some composer dependencies requires php `5.3.9`, i'll change the requirements to php `5.3.9` and publish that in version `1.1.0`.

In any case we think version `5.3.x` should be progressivly abandonned so in my opinion this is not very problematic.

**Comment by vinkla** [comment]
Remember to update `5.3.3` to `5.3.9` in the travis file.

**Comment by vinkla** [comment]
:+1:

**Comment by bgaillard** [comment]
Argh, yes it seems `5.3.9` is not supported by Travis, so version `1.1.0` of `php-pushwoosh` will simply abandon PHP `5.3.x`...

**Comment by vinkla** [comment]
Yeah, I think maybe travis only have 5.3.3 to be honest. Good that you're dropping `5.3` :+1:

**Pull request merged**
